# Generated by Django 2.0.1 on 2018-03-16 22:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_handle', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('trans_type', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
